### ISSUE TITLE
Comment problem in SkyTube APK 

### ISSUE THREAD

**Issue by MBZ-07** [ram-on/SkyTube#863]
Hi, SkyTube version cannot scrap comments.
Plus, do you have any solution to export my subscriptions from YouTube (the older method mentioned in the app doesn't work).

**Comment by gzsombor** [comment]
Thanks, luckily it's already fixed in newer NewPipeExtractor.

**Comment by MBZ-07** [comment]
Good, please do you have any solution to subs export from youtube ?

**Comment by gzsombor** [comment]
No, I don't have, no one contributed anything.

> Good, please do you have any solution to subs export from youtube ?
> […](#)
> On December 26, 2020 10:41:47 PM GMT+01:00, Zsombor ***@***.***> wrote: Thanks, luckily it's already fixed in newer NewPipeExtractor. -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#863 (comment)](https://github.com/ram-on/SkyTube/issues/863#issuecomment-751398841)

**Comment by MBZ-07** [comment]
Ok, BTW the bug still exist in v2.975 (Error:413 request entity too large"). Tested now.

**Comment by gzsombor** [comment]
Yeah, accidentally I set a wrong milestone label, sorry

**Comment by MBZ-07** [comment]
Ah Ok, when the new version of f-droid will be released then ?

**Comment by MBZ-07** [comment]
Could you add support for json file youtube subs import ? I've found a new way to import subs check that : https://newpipe.net/FAQ/tutorials/import-export-data/#import-youtube
